// <auto-generated />
using System;
using Makyr.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Makyr.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231021183621_MadeCertainPropsNullableInGpuTable")]
    partial class MadeCertainPropsNullableInGpuTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Makyr.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Makyr.Models.GraphicsCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BaseClock")
                        .HasColumnType("int");

                    b.Property<int?>("BoostClock")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BusType")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Connectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CudaCores")
                        .HasColumnType("int");

                    b.Property<double?>("Depth")
                        .HasColumnType("float");

                    b.Property<string>("Directx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HdmiPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturingWarrenty")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryClockSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MemorySize")
                        .HasColumnType("int");

                    b.Property<string>("MemoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OpenGL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedPsu")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceWarrenty")
                        .HasColumnType("int");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GraphicsCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f0aa452-c379-4d72-a640-a8ca8c7b75f2"),
                            BaseClock = 1607,
                            BoostClock = 1733,
                            Brand = "Nvidia",
                            BusType = 256,
                            Condition = "New",
                            Connectors = "8-pin",
                            CudaCores = 2560,
                            Depth = 38.100000000000001,
                            Directx = "DirectX 12",
                            DisplayPort = "3",
                            HdmiPort = "1",
                            Height = 111.2,
                            IsInStock = true,
                            ManufacturingWarrenty = 12,
                            MemoryClockSpeed = 10,
                            MemorySize = 8,
                            MemoryType = "GDDR5",
                            Model = "GTX 1080",
                            OpenGL = "OpenGL 4.5",
                            Price = 599.99000000000001,
                            ProductCode = "ABC123",
                            Quantity = 3,
                            RecommendedPsu = 500,
                            ServiceWarrenty = 0,
                            Width = 267.69999999999999
                        },
                        new
                        {
                            Id = new Guid("cd8bfc8e-81da-4dbe-ae21-cdcbabe50398"),
                            BaseClock = 1605,
                            BoostClock = 1905,
                            Brand = "AMD",
                            BusType = 256,
                            Condition = "Used",
                            Connectors = "8-pin",
                            CudaCores = 0,
                            Depth = 40.0,
                            Directx = "DirectX 12",
                            DisplayPort = "3",
                            HdmiPort = "1",
                            Height = 116.59999999999999,
                            IsInStock = true,
                            ManufacturingWarrenty = 0,
                            MemoryClockSpeed = 14,
                            MemorySize = 8,
                            MemoryType = "GDDR6",
                            Model = "RX 5700 XT",
                            OpenGL = "OpenGL 4.6",
                            Price = 299.99000000000001,
                            ProductCode = "XYZ456",
                            Quantity = 10,
                            RecommendedPsu = 600,
                            ServiceWarrenty = 6,
                            Width = 268.0
                        },
                        new
                        {
                            Id = new Guid("e15ceede-ba68-47e4-b58f-74791ada0369"),
                            BaseClock = 1410,
                            BoostClock = 1695,
                            Brand = "MSI",
                            BusType = 256,
                            Condition = "New",
                            Connectors = "8-pin",
                            CudaCores = 4864,
                            Depth = 39.0,
                            Directx = "DirectX 12",
                            DisplayPort = "3",
                            HdmiPort = "1",
                            Height = 115.0,
                            IsInStock = false,
                            ManufacturingWarrenty = 24,
                            MemoryClockSpeed = 14,
                            MemorySize = 8,
                            MemoryType = "GDDR6",
                            Model = "RTX 3060 Ti",
                            OpenGL = "OpenGL 4.6",
                            Price = 449.99000000000001,
                            ProductCode = "LMN789",
                            Quantity = 0,
                            RecommendedPsu = 650,
                            ServiceWarrenty = 0,
                            Width = 245.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
